#!/usr/bin/env bash
# scaffold.sh — bootstrap a Python data-science / analytics project
#
# Creates a uv-managed workspace with:
#   packages/  — reusable library code (src layout, uv_build backend)
#   apps/      — runnable apps / CLI entry points
#   notebooks/ — Jupyter exploration
#   docs/      — methodology, metrics, assumptions, limitations, data sources
#   data/      — raw / interim / processed / external (gitignored)
#   outputs/   — figures, map layers, marts (gitignored)
#   .vscode/   — settings, launch, tasks, code-workspace
#   .github/   — CI workflow
#
# Usage:
#   ./scaffold.sh my-project-name
#
# Prerequisites: uv (https://docs.astral.sh/uv/getting-started/installation/)

set -euo pipefail

# ---------------------------------------------------------------------------
# Args
# ---------------------------------------------------------------------------
if [ "$#" -ne 1 ]; then
  echo "Usage: $0 <project-name>"
  echo ""
  echo "Scaffolds a uv-managed Python data-science workspace."
  exit 1
fi

PROJECT="$1"

# Git author info (used for CITATION.cff and GitHub URL)
GIT_NAME="$(git config user.name  || echo 'Your Name')"
GIVEN="${GIT_NAME%% *}"
FAMILY="${GIT_NAME#* }"
[ "$GIVEN" = "$FAMILY" ] && FAMILY=""
GH_USER="$(git config github.user 2>/dev/null || echo "${USER}")"
TODAY="$(date +%Y-%m-%d)"

echo "🚀  Scaffolding ${PROJECT} ..."

# ---------------------------------------------------------------------------
# Top-level directories
# ---------------------------------------------------------------------------
mkdir -p "${PROJECT}"
cd "${PROJECT}"

mkdir -p \
  .github/workflows \
  .vscode \
  apps \
  binder \
  data/{raw,interim,processed,external} \
  docs \
  notebooks \
  outputs/{figures,map_layers} \
  packages \
  tests

# .gitkeep for gitignored empty dirs
for d in data/{raw,interim,processed,external} outputs/{figures,map_layers}; do
  touch "${d}/.gitkeep"
done

# ---------------------------------------------------------------------------
# .gitignore — fetch GitHub's Python template + project-specific extras
# GitHub uses this same file when you select "Python" in the repo creation UI.
# Ref: https://github.com/github/gitignore/blob/main/Python.gitignore
# ---------------------------------------------------------------------------
echo "   ↳ .gitignore (GitHub Python template + extras)"
if ! curl -fsSL "https://raw.githubusercontent.com/github/gitignore/main/Python.gitignore" \
  -o .gitignore 2>/dev/null; then
  # Offline fallback — essential entries only
  cat > .gitignore <<'FALLBACK'
__pycache__/
*.py[codz]
*$py.class
*.so
build/
dist/
*.egg-info/
.eggs/
.venv/
.env
htmlcov/
.coverage
.pytest_cache/
.mypy_cache/
.ruff_cache/
.ipynb_checkpoints/
FALLBACK
fi

cat >> .gitignore <<'EXTRA'

# ---------- project-specific ----------
# VS Code local history
.history/

# Output artifacts (regenerated by `make outputs`)
**/outputs/
EXTRA

# ---------------------------------------------------------------------------
# binder/ — Binder config for launching notebooks on mybinder.org
#
# repo2docker would try to `pip install .` if it sees the root pyproject.toml,
# which fails because the root is a virtual workspace (package = false).
# Placing config in binder/ makes repo2docker ignore the root pyproject.toml.
# We use uv to install deps from the single source of truth (pyproject.toml).
# ---------------------------------------------------------------------------
echo "   ↳ binder/"
cat > binder/runtime.txt <<'TXT'
python-3.13
TXT

cat > binder/postBuild <<'BASH'
#!/usr/bin/env bash
set -euo pipefail

# Bootstrap uv (fast, single-binary installer).
pip install --no-cache-dir uv==0.10.9

# Install notebook deps from the single source of truth (pyproject.toml).
uv export --no-hashes --group notebooks | uv pip install --system --no-cache -r -

# Install workspace packages (if any exist yet).
for pkg in packages/*/pyproject.toml; do
    [ -f "$pkg" ] && uv pip install --system --no-cache "./$(dirname "$pkg")"
done
BASH
chmod +x binder/postBuild

# ---------------------------------------------------------------------------
# uv init — workspace root (virtual package, not installable itself)
# Docs: https://docs.astral.sh/uv/concepts/workspaces/
# ---------------------------------------------------------------------------
echo "   ↳ uv init (workspace root)"
uv init \
  --name "${PROJECT}" \
  --description "A scaffolded data-science project." \
  --author-from git \
  --vcs git \
  --python 3.13 \
  --managed-python

# ---------------------------------------------------------------------------
# pyproject.toml — rewrite with workspace config, dep groups, tool settings
#
# Key uv docs referenced here:
#   Workspaces:    https://docs.astral.sh/uv/concepts/workspaces/
#   Dep groups:    https://docs.astral.sh/uv/concepts/dependencies/#dependency-groups
#   Build backend: https://docs.astral.sh/uv/concepts/build-backend/
# ---------------------------------------------------------------------------
echo "   ↳ pyproject.toml"
cat > pyproject.toml <<TOML
[project]
name = "${PROJECT}"
version = "0.1.0"
description = "A scaffolded data-science project."
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "mypy>=1.13.0",
    "pre-commit>=4.0.1",
    "pytest>=8.3.3",
    "pytest-cov>=6.0.0",
    "ruff>=0.7.0",
]
notebooks = [
    "ipykernel>=6.29.0",
    "pandas>=3.0.1",
    "numpy>=2.4.2",
    "matplotlib>=3.10.0",
    "seaborn>=0.13.2",
    "plotly>=6.0.0",
    "requests>=2.32.0",
    "nbformat>=5.10.0",
]

[build-system]
requires = ["uv_build>=0.10.4,<0.11.0"]
build-backend = "uv_build"

[tool.uv]
package = false
default-groups = ["dev"]

[tool.uv.workspace]
members = ["packages/*", "apps/*"]

[tool.pytest.ini_options]
minversion = "8.0"
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = "-ra --strict-markers --strict-config"

[tool.ruff]
src = [
    "packages/**/src",
    "packages/**/tests",
    "apps/*/*.py",
    "apps/**/src",
    "apps/**/tests",
]
extend-exclude = [".history"]
line-length = 120
target-version = "py313"

[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP", "SIM", "W"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.pylint.format]
max-line-length = 120

[tool.mypy]
files = ["."]
python_version = "3.13"
strict = true
warn_unused_configs = true
warn_unused_ignores = true
warn_return_any = true
disallow_untyped_defs = true
no_implicit_optional = true
TOML

# Remove the hello.py that uv init creates
rm -f hello.py main.py

# ---------------------------------------------------------------------------
# .pre-commit-config.yaml
# ---------------------------------------------------------------------------
echo "   ↳ .pre-commit-config.yaml"
cat > .pre-commit-config.yaml <<'YAML'
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
YAML

# ---------------------------------------------------------------------------
# Makefile (generic targets — add project-specific targets below the line)
# ---------------------------------------------------------------------------
echo "   ↳ Makefile"
cat > Makefile <<'MAKE'
.PHONY: setup sync test lint format typecheck check precommit clean

setup: sync
	uv run pre-commit install

sync:
	uv sync --all-packages --all-extras --all-groups

test:
	uv run pytest -q

lint:
	uv run ruff check . --fix

format:
	uv run ruff format .

typecheck:
	uv run mypy

check: format lint typecheck test

precommit:
	uv run pre-commit run --all-files

clean:
	rm -rf .pytest_cache .ruff_cache .mypy_cache htmlcov .coverage coverage.xml
	rm -rf outputs/
	mkdir -p outputs/{figures,map_layers}
	touch outputs/{figures,map_layers}/.gitkeep
MAKE

# ---------------------------------------------------------------------------
# .github/workflows/ci.yml
# ---------------------------------------------------------------------------
echo "   ↳ .github/workflows/ci.yml"
cat > .github/workflows/ci.yml <<'GHA'
name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  quality-gate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Set up uv
        uses: astral-sh/setup-uv@v4

      - name: Install dependencies
        run: make sync

      - name: Ruff
        run: make lint

      - name: Mypy
        run: make typecheck

      - name: Pytest
        run: make test
GHA

# ---------------------------------------------------------------------------
# pyrightconfig.json (Pylance / pyright in VS Code)
# ---------------------------------------------------------------------------
echo "   ↳ pyrightconfig.json"
cat > pyrightconfig.json <<'JSON'
{
    "venvPath": ".",
    "venv": ".venv",
    "include": [
        "packages/**/src",
        "packages/**/tests",
        "apps/**/src",
        "apps/**/tests",
        "apps/**/*.py"
    ],
    "extraPaths": [
        "packages/**/src",
        "packages/**/tests",
        "apps/**/src",
        "apps/**/tests",
        "apps/**/*.py"
    ],
    "typeCheckingMode": "strict",
    "reportMissingTypeStubs": false,
    "reportUnknownMemberType": false
}
JSON

# ---------------------------------------------------------------------------
# .vscode/settings.json
# ---------------------------------------------------------------------------
echo "   ↳ .vscode/settings.json"
cat > .vscode/settings.json <<'JSON'
{
    "python.defaultInterpreterPath": "${workspaceFolder}/.venv/bin/python",
    "python.terminal.activateEnvironment": true,
    "python.testing.pytestEnabled": true,
    "python.testing.unittestEnabled": false,
    "python.testing.pytestArgs": [
        "packages/",
        "apps/"
    ],
    "python.testing.cwd": "${workspaceFolder}",
    "python.analysis.autoImportCompletions": true,
    "python.analysis.diagnosticSeverityOverrides": {
        "reportMissingTypeStubs": "none",
        "reportUnknownMemberType": "none"
    },
    "ruff.lineLength": 120,
    "ruff.nativeServer": "on",
    "[python]": {
        "editor.defaultFormatter": "charliermarsh.ruff",
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.fixAll.ruff": "always",
            "source.organizeImports.ruff": "always"
        }
    },
    "makefile.configureOnOpen": false
}
JSON

# ---------------------------------------------------------------------------
# <project>.code-workspace
# ---------------------------------------------------------------------------
echo "   ↳ ${PROJECT}.code-workspace"
cat > "${PROJECT}.code-workspace" <<JSON
{
    "folders": [
        {
            "path": "."
        }
    ],
    "settings": {
        "python.defaultInterpreterPath": "\${workspaceFolder}/.venv/bin/python",
        "python.terminal.activateEnvironment": true,
        "python.testing.pytestEnabled": true,
        "python.testing.unittestEnabled": false,
        "python.testing.pytestArgs": [
            "packages",
            "apps"
        ],
        "python.testing.cwd": "\${workspaceFolder}",
        "python.analysis.extraPaths": [
            "\${workspaceFolder}/packages/**/src",
            "\${workspaceFolder}/packages/**/tests",
            "\${workspaceFolder}/apps/*/",
            "\${workspaceFolder}/apps/**/src",
            "\${workspaceFolder}/apps/**/tests"
        ],
        "ruff.nativeServer": "on"
    },
    "extensions": {
        "recommendations": [
            "ms-python.python",
            "ms-python.vscode-pylance",
            "charliermarsh.ruff"
        ]
    }
}
JSON

# ---------------------------------------------------------------------------
# CITATION.cff (author info from git config)
# ---------------------------------------------------------------------------
echo "   ↳ CITATION.cff"
cat > CITATION.cff <<CFF
cff-version: 1.2.0
title: ${PROJECT}
message: "If you use this repo, please cite it."
type: software
authors:
  - family-names: "${FAMILY}"
    given-names: "${GIVEN}"
version: 0.1.0
date-released: ${TODAY}
license: GPL-3.0-or-later
CFF

# ---------------------------------------------------------------------------
# docs/ — starter documentation templates
# ---------------------------------------------------------------------------
echo "   ↳ docs/"

cat > docs/METHODS.md <<'MD'
# Methods

<!-- Describe computation methodology, formulas, and rationale here. -->
MD

cat > docs/METRIC_DEFINITIONS.md <<'MD'
# Metric Definitions

All metrics are computed at **(region, period)** granularity unless explicitly stated.

<!-- Define each metric: name, formula, units, config references. -->
MD

cat > docs/ASSUMPTIONS.md <<'MD'
# Assumptions

<!-- List working assumptions. Update as the project evolves. -->

- ...
MD

cat > docs/LIMITATIONS.md <<'MD'
# Limitations and Failure Modes

<!-- Document known limitations, edge cases, and failure modes. -->

- ...
MD

cat > docs/DATA_SOURCES.md <<'MD'
# Data Sources

<!-- Document each data source: origin, format, update cadence, license. -->

## DEMO mode (default)

- Synthetic data generated deterministically (seeded).
- DEMO mode exists to validate the pipeline end-to-end without external dependencies.

## Real-data mode (planned)

- ...
MD

cat > docs/DATA_GENERATION.md <<'MD'
# Data Generation (DEMO mode)

<!-- Explain how synthetic / demo data is created, seeds, distributions used. -->
MD

cat > docs/DECISIONS_MEMO_TEMPLATE.md <<'MD'
# Decision Memo (Template)

## Context
## Key findings
## Recommended actions
## Caveats
MD

# ---------------------------------------------------------------------------
# README.md
# ---------------------------------------------------------------------------
echo "   ↳ README.md"
cat > README.md <<MD
# ${PROJECT}

![CI](https://github.com/${GH_USER}/${PROJECT}/actions/workflows/ci.yml/badge.svg)
[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/${GH_USER}/${PROJECT}/main?labpath=notebooks)

> _One-line project description._

## Quickstart

\`\`\`sh
make setup    # create venv, install deps, set up pre-commit
make check    # format + lint + typecheck + test
\`\`\`

## Project layout

\`\`\`
packages/     # reusable library code (src layout, uv_build backend)
apps/         # runnable apps / CLI entry points
notebooks/    # Jupyter exploration
docs/         # methodology, metrics, assumptions, limitations
data/         # raw / interim / processed / external (gitignored)
outputs/      # figures, map layers, marts (gitignored)
\`\`\`

## Key docs

- [docs/METHODS.md](docs/METHODS.md)
- [docs/METRIC_DEFINITIONS.md](docs/METRIC_DEFINITIONS.md)
- [docs/ASSUMPTIONS.md](docs/ASSUMPTIONS.md)
- [docs/LIMITATIONS.md](docs/LIMITATIONS.md)
- [docs/DATA_SOURCES.md](docs/DATA_SOURCES.md)

## About the scaffolding

This project structure comes from a personal starter template. It's set up following the
actual tooling docs and adjusted to how I work:

- [uv workspaces](https://docs.astral.sh/uv/concepts/workspaces/) for the monorepo layout
- [uv dependency groups](https://docs.astral.sh/uv/concepts/dependencies/#dependency-groups)
  to separate dev / notebook / production deps
- [uv build backend](https://docs.astral.sh/uv/concepts/build-backend/) (\`uv_build\`)
  so packages are installable without setuptools
- [ruff](https://docs.astral.sh/ruff/) for linting + formatting in one tool
- [mypy strict](https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-strict)
  for type safety

See [DEVELOP.md](DEVELOP.md) for how to add packages, manage dependencies, and work with uv.

## License

GPLv3 (see LICENSE).
MD

# ---------------------------------------------------------------------------
# DEVELOP.md — developer guide for working with uv in this project
# ---------------------------------------------------------------------------
echo "   ↳ DEVELOP.md"
cat > DEVELOP.md <<'MD'
# Developer Guide

This project uses **[uv](https://docs.astral.sh/uv/)** for all Python and dependency
management. If you haven't used uv before, the key docs are:

- [Installing uv](https://docs.astral.sh/uv/getting-started/installation/)
- [Workspaces](https://docs.astral.sh/uv/concepts/workspaces/)
- [Dependency groups](https://docs.astral.sh/uv/concepts/dependencies/#dependency-groups)
- [Build backend](https://docs.astral.sh/uv/concepts/build-backend/)

---

## Initial setup

```sh
make setup        # runs uv sync + pre-commit install
```

This creates `.venv/`, installs all workspace members, and sets up the git hooks.

## Adding a new workspace package

uv workspaces let you split code into independently-versioned packages under one repo.
Our convention: library code goes in `packages/`, runnable apps in `apps/`.

### 1. Create the package

```sh
# From the repo root:
uv init --package packages/my_new_package \
  --build-backend uv
```

This creates `packages/my_new_package/` with:
- `pyproject.toml` (using `uv_build` backend — no setuptools/hatch needed)
- `src/my_new_package/__init__.py`

The `--build-backend uv` flag tells uv to use its own
[build backend](https://docs.astral.sh/uv/concepts/build-backend/) (`uv_build`), which is
lighter than setuptools or hatch and handles the `src/` layout automatically.

### 2. Verify it's a workspace member

Check the root `pyproject.toml`:

```toml
[tool.uv.workspace]
members = ["packages/*", "apps/*"]
```

The glob `packages/*` picks up the new package automatically. If you used a nested path
like `packages/sub/my_pkg`, you'd need `packages/**` or an explicit entry.

### 3. Add dependencies to the new package

```sh
# Runtime dep (goes into the package's own pyproject.toml):
uv add --package my_new_package pandas

# If you need another workspace member as a dep:
uv add --package my_new_package my_other_package
```

uv resolves workspace-internal references via
[`tool.uv.sources`](https://docs.astral.sh/uv/concepts/workspaces/#configuring-workspaces):

```toml
[tool.uv.sources]
my_other_package = { workspace = true }
```

### 4. Sync

```sh
uv sync --all-packages --all-extras --all-groups
# or just:
make sync
```

## Dependency groups

We use [dependency groups](https://docs.astral.sh/uv/concepts/dependencies/#dependency-groups)
(PEP 735) to keep deps organized without polluting the main install:

| Group | Purpose | When installed |
|---|---|---|
| `dev` | pytest, mypy, ruff, pre-commit | always (`default-groups`) |
| `notebooks` | ipykernel, pandas, plotly, matplotlib, etc. | `uv sync --group notebooks` or `--all-groups` |

### Adding a dep to a group

```sh
# Add to the notebooks group (defined in root pyproject.toml):
uv add --group notebooks folium

# Add to dev:
uv add --group dev hypothesis
```

Groups live in the **root** `pyproject.toml` under `[dependency-groups]`.
They're installed into the shared `.venv/` — not per-package.

## Running things

All commands go through `uv run` to ensure the right venv is active:

```sh
uv run pytest                  # tests
uv run ruff check . --fix      # lint
uv run mypy                    # type check
uv run python -m my_package    # run a module
```

Or use the Makefile shortcuts:

```sh
make test       # uv run pytest -q
make lint       # uv run ruff check . --fix
make typecheck  # uv run mypy
make check      # format + lint + typecheck + test
```

## Adding a CLI entry point

In a package's `pyproject.toml`:

```toml
[project.scripts]
my-cli = "my_package.cli:main"
```

After `uv sync`, the command `my-cli` is available via `uv run my-cli` or directly in the
activated venv.

## Notebooks

Notebooks go in `notebooks/`. The `notebooks` dependency group provides the kernel and
common data-science packages. To use it:

```sh
uv sync --group notebooks
```

Then select the `.venv/bin/python` kernel in VS Code / Jupyter.

Notebooks are **not** type-checked or linted by CI — they're exploratory. Keep reusable
logic in `packages/` and import it from notebooks.

## Pre-commit & CI

Pre-commit runs ruff (lint + format) and basic file checks on every commit.
CI (`.github/workflows/ci.yml`) runs the full `make sync` → lint → typecheck → test
pipeline on push/PR.

## Project conventions

- **src layout** for all packages (`packages/foo/src/foo/`)
- **Line length**: 120 (ruff + pylint + editors all configured)
- **Type checking**: mypy strict mode — add `# type: ignore[code]` with a comment when needed
- **Quotes**: double (`"`) — enforced by ruff format
- **Tests**: mirror the package structure under `tests/` at the repo root, or `packages/foo/tests/`

## Creating a GitHub template repo from this

If you want to reuse this scaffold as a GitHub template:

1. Push this repo to GitHub (or create a new repo from the scaffold output)
2. Go to **Settings → General → Template repository** and check the box
3. Now anyone (including you) can click **"Use this template"** on GitHub to create a new
   repo with the same file structure
4. After cloning the new repo, run:
   ```sh
   # Update project name in pyproject.toml, CITATION.cff, *.code-workspace, README
   # Then:
   make setup
   ```

Alternatively, keep `scaffold.sh` in a gist or standalone repo and run it directly:

```sh
curl -fsSL https://raw.githubusercontent.com/YOU/ds-template/main/scaffold.sh | bash -s my-project
```
MD

# ---------------------------------------------------------------------------
# Placeholder main.py
# ---------------------------------------------------------------------------
cat > main.py <<'PY'
"""Project entry-point — wire up CLI or ad-hoc scripts here."""


def main() -> None:
    print("Hello from ${PROJECT}!")


if __name__ == "__main__":
    main()
PY

# ---------------------------------------------------------------------------
# Placeholder test
# ---------------------------------------------------------------------------
cat > tests/__init__.py <<'PY'
PY

cat > tests/test_placeholder.py <<'PY'
"""Placeholder test — proves the test runner works."""


def test_placeholder() -> None:
    assert True
PY

# ---------------------------------------------------------------------------
# Sync
# ---------------------------------------------------------------------------
echo "   ↳ uv sync"
uv sync --all-packages --all-extras --all-groups

echo ""
echo "✅  ${PROJECT} scaffolded successfully."
echo ""
echo "Next steps:"
echo "  cd ${PROJECT}"
echo "  make setup          # install pre-commit hooks"
echo "  code ${PROJECT}.code-workspace"
echo ""
echo "To add your first package:"
echo "  uv init --package packages/my_package --build-backend uv"
echo "  uv sync --all-packages"
echo ""
echo "Push to GitHub:"
echo "  git add ."
echo "  git commit -m \"first commit\""
echo "  git branch -M main"
echo "  git remote add origin https://github.com/${GH_USER}/${PROJECT}.git"
echo "  git push -u origin main"
echo ""
echo "See DEVELOP.md for the full developer guide."